apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-users-job
spec:
  schedule: "0 0 * * *"  # 毎日午前0時に実行
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-users
            image: asia-northeast1-docker.pkg.dev/plesio-infra-407706/plesio-infra-407706-repository/plesio-cronjob:latest
            env:
              - name: MYSQL_USER
                value: "admin"
              - name: MYSQL_PASSWORD
                value: "kumayama0211"
              - name: MYSQL_DB
                value: "main"
              - name: MYSQL_PORT 
                value: "3306"
              - name: MYSQL_HOST
                value: "127.0.0.1"
          - name: cloud-sql-proxy
            image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
            args:
              - "--private-ip"
              - "--structured-logs"
              - "--port=3306"
              - "plesio-infra-407706:asia-northeast1:mysql-prod"
            securityContext:
              runAsNonRoot: true
          restartPolicy: OnFailure
